### ISSUE TITLE
Struggling with getting DiscPage to work with newest Discourse

### ISSUE THREAD

**Issue by madsl** [sylque/discpage#38] opened 2023-12-29 19:05 UTC
Recently upgraded to discourse to todays version (https://github.com/discourse/discourse/commit/406f4c9e807ac483415fff22e9f187baa2063fe5) after a long time of no updates, and it seems like DiscPage might have stopped working in the meantime? Can't get it to show any content when visiting a DiscPage-enabled thread, the page stays blank except for the menus. I can get something to show if I toggle off DiscPage in the menu. If I try the page in a not-logged in session on a public page, I can't get it to show anything at all except the menu, and you have no way of toggling DiscPage.

**Comment by sylque** [comment] 2023-12-30 10:23
Thanks for reporting, @madsl . I will work  on this on Monday.

**Comment by sylque** [comment] 2024-01-01 17:05
Fixed in v1.0.58.
The issue was caused by the HTML class ".category-name" having been renamed to ".badge-category__name" in Discourse.

**Closed as completed by sylque** 2024-01-01 17:05 UTC

**Comment by madsl** [comment] 2024-01-01 17:50
@sylque great work, works beautifully!

Due to it working, I found another bug, but this time in discourse-home-page...
