### ISSUE TITLE
Trouble Creating a Topic Connected to a Page

### ISSUE THREAD

**Issue by noobishme** [sylque/discpage#30] opened 2022-09-13 19:00 UTC
I have a testing instance on my site at ...

https://noobish.me/t/chapter-1-in-the-beginning/255

When I click the orange balloons the page does slides in to halves ...

![image](https://user-images.githubusercontent.com/106134379/189986901-f774f350-27b1-4b60-8bae-ad3456687986.png)

Then when I click the + New Topic button in the Right panel  the Topic editor does slide up from the bottom, so I use that to write my Topic …

![image](https://user-images.githubusercontent.com/106134379/189987073-1b76967e-48f0-4c02-8d03-28383722c0e9.png)

… but then after I save it, it’s not connected to the Page Topic, and still there is no Topic list in the Right panel…

![image](https://user-images.githubusercontent.com/106134379/189987206-697da26d-78f2-47a5-b915-fe32867f4f2d.png)

**Comment by sylque** [comment] 2022-09-13 19:28
Thanks @noobishme .

I cannot reproduce this issue on my own Discourse instances. Please accept my registration so that I can try on yours.

Also, would you please set `discpage hide tags=checked` in your Discourse settings and let me know if the behavior is the same? Thanks.

**Comment by noobishme** [comment] 2022-09-13 19:47
Done and done ... the behavior is the same.

![Screenshot 2022-09-13 134419](https://user-images.githubusercontent.com/106134379/189995550-56548b31-39db-4c04-ace4-8977a4eea1fc.png)

**Comment by sylque** [comment] 2022-09-13 20:47
Please do the following :
1. Uncheck the "discpage hide tags" setting (in order to come back to the previous situation).
2. Install the latest version of DiscPage (I've just release a new version). This won't fix your issue, but might help tracking it.
3. Try to create a new topic in a balloon and tell me if it works. If it doesn't, please provide a screenshot of the "Topic editor" (whose official name is "the composer":-)
4. Ensure you are logged-in as a Discourse admin and start step 3 again. But this time, just open the composer, press Alt+a (this enters DiscPage debug mode) and take another screenshot.
Thanks.

**Comment by noobishme** [comment] 2022-09-13 21:48
This is a second test topic. I have 
1. Unchecked the "discpage hide tags" setting (in order to come back to the previous situation).

2. Installed the latest version of DiscPage and Discourse...
![image](https://user-images.githubusercontent.com/106134379/190015492-8ff6e803-eebb-4fcd-9f00-fbcaef0f2124.png)

3. Here is a screenshot of the Composer as I create the topic after clicking the orange balloon...
![image](https://user-images.githubusercontent.com/106134379/190015520-00f7e749-614e-46ba-9301-6db686ae67ca.png)
... and here is a screenshot of the result (still did not work) ...
![image](https://user-images.githubusercontent.com/106134379/190015624-8e0c3fee-b33e-4b2f-aeaa-7ee0a1509695.png)

4. Screenshot after just opened the composer and pressed Alt+a ...
![image](https://user-images.githubusercontent.com/106134379/190015675-2b58f318-3dac-4be9-95ce-cf0b3a6694b2.png)

**Comment by sylque** [comment] 2022-09-13 22:13
Thanks a lot.

There's definitely something odd with your Discourse instance.

In Discourse, when you are on a tag page, the topic composer should have the tag preselected. For example:

1. Go to https://meta.discourse.org/tag/docker (this is the page for tag "docker" on Discourse Meta)

2. Click the "New Topic" button. You should get this:
![image](https://user-images.githubusercontent.com/42490951/190017625-e448f435-edbc-45e2-a9e6-a89d04ae71d0.png)
See how the tag selector is prefilled with "docker".

Now try to do the same with your own Discourse:

1. Go to https://noobish.me/tag/mom (this is the page for tag "mom")

2. Click the "New Topic" button. You get this:
![image](https://user-images.githubusercontent.com/42490951/190018090-6336d9af-0e8a-4345-9ef0-660814e068a3.png)
The tag selector is empty!

There might be a plugin messing up with Discourse. Please disable plugins one at a time (starting with DiscPage) and run the above test again, until the tag selector is correctly prefilled.

**Comment by noobishme** [comment] 2022-09-13 22:18
Will do!

**Comment by noobishme** [comment] 2022-09-13 22:59
You nailed it. It's most definitely the

https://meta.discourse.org/t/layouts-plugin/55208

https://plugins.discourse.pavilion.tech/c/discourse-layouts/33

https://github.com/paviliondev/discourse-layouts

![Screenshot 2022-09-13 165446](https://user-images.githubusercontent.com/106134379/190023884-39d8d21e-9312-4940-9b00-3a10fccfd165.png)

My nOObish.me site is currently using the Layouts Plugin along side the Layouts Category List Widget (theme component). As long as the Layouts Plugin is enabled the problem exists (with or without the Layouts Category List Widget theme component.)

**Comment by noobishme** [comment] 2022-09-13 23:20
OK I deleted the old Tag Groups, cleared my Cloudflare cache, created a new "Chapter" (DiscPage) topic (**Chapter 2: In the Middle**) copying the same content in the composer from the Chapter 1 page.

The **+ New Topic** button is greyed-out and unclickable, so I can't test further until that is resolved...

![Screenshot 2022-09-13 171341](https://user-images.githubusercontent.com/106134379/190026168-89c94a41-7551-423b-9cf4-431ec99479bc.png)

**Comment by sylque** [comment] 2022-09-14 12:07
Glad this is solved.

The greyd-out "New Topic" button is a new issue, I will create another post for it.

**Closed as completed by sylque** 2022-09-14 12:07 UTC
